[[disallowed-types]]
path = 'std::collections::HashMap'
reason = 'consider using ahash::AHashMap'

[[disallowed-types]]
path = 'std::collections::HashSet'
reason = 'consider using ahash::AHashSet'

[[disallowed-methods]]
path = 'std::option::Option::unwrap'
reason = 'consider providing context with std::option::Option::expect'

[[disallowed-methods]]
path = 'std::result::Result::unwrap'
reason = 'consider providing context with std::result::Result::expect'
